name: belajar_dart_application
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0 <3.0.0'

publish_to: none

dependencies:
  belajar_dart_library: 1.5.0
  # path: ^1.8.0
  # belajar_dart_library:
  #   git: 
  #     url: git@github.com:adexRepo/myLanguage.git
  #     ref: 1.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
